name: hometest
description: "Test project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  floor: ^1.2.0
  get_it: ^8.0.1
  flutter_bloc: ^8.1.2 # for Cubit
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0
  floor_generator: ^1.3.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
